### ISSUE TITLE
cannot get difference from Schemafile containing bigserial or serial

### ISSUE THREAD

**Issue by altblanc** [winebarrel/ridgepole#342]
I'm using ridgepole 0.8.12 in my Rails application.
export by `ridgepole -c database.yml -E development --export --output Schemafile` from the database created from the ddl like below:
  ```ruby
  CREATE TABLE some_table(
    primary_id    bigserial         NOT NULL,
    secondary_id            bigserial         NOT NULL,
    column1                  varchar(255)              NOT NULL,
    created_at            timestamp         NOT NULL,
    updated_at            timestamp         NOT NULL,
    CONSTRAINT some_table_pkey PRIMARY KEY (primary_id)
  )
  ```
and result is:
  ```ruby
  create_table "some_table", primary_key: "primary_id", force: :cascade do |t|
    t.bigserial "secondary_id", null: false
    t.string "column1", limit: 255, null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end
  ```
but when I tried to get diff between this Schemafile and another Schemafile, ridgepole return error:
`[ERROR] undefined method 'bigserial' for #<Ridgepole::DSLParser::TableDefinition:0x000055b41f08c180>`

Can I use ridgepole to the database which has bigserial(or serial) columns? How should I do?

**Comment by winebarrel** [comment]
Please write a stack trace of the error with `--debug` option.

And please also write the following:
- `ruby -v`
- `ridgepove -v`
- postgresql version

**Comment by altblanc** [comment]
Stack trace is below:
```bash
$ bundle exec ridgepole -c config/database.yml -E development --diff config/database.yml db/Schemafile --debug
bundler: failed to load command: ridgepole (/home/user/Desktop/application/vendor/bundle/ruby/2.5.0/bin/ridgepole)
NoMethodError: undefined method `bigserial' for #<Ridgepole::DSLParser::TableDefinition:0x0000561475db0148>
  db/Schemafile:23:in `block in eval'
  /home/user/Desktop/application/vendor/bundle/ruby/2.5.0/gems/ridgepole-0.8.12/lib/ridgepole/dsl_parser/context.rb:37:in `create_table'
  db/Schemafile:22:in `eval'
  /home/user/Desktop/application/vendor/bundle/ruby/2.5.0/gems/ridgepole-0.8.12/lib/ridgepole/dsl_parser/context.rb:18:in `instance_eval'
  /home/user/Desktop/application/vendor/bundle/ruby/2.5.0/gems/ridgepole-0.8.12/lib/ridgepole/dsl_parser/context.rb:18:in `eval'
  /home/user/Desktop/application/vendor/bundle/ruby/2.5.0/gems/ridgepole-0.8.12/lib/ridgepole/dsl_parser.rb:10:in `parse'
  /home/user/Desktop/application/vendor/bundle/ruby/2.5.0/gems/ridgepole-0.8.12/lib/ridgepole/client.rb:78:in `load_definition'
  /home/user/Desktop/application/vendor/bundle/ruby/2.5.0/gems/ridgepole-0.8.12/lib/ridgepole/client.rb:50:in `diff'
  /home/user/Desktop/application/vendor/bundle/ruby/2.5.0/gems/ridgepole-0.8.12/bin/ridgepole:268:in `<top (required)>'
  /home/user/Desktop/application/vendor/bundle/ruby/2.5.0/bin/ridgepole:23:in `load'
  /home/user/Desktop/application/vendor/bundle/ruby/2.5.0/bin/ridgepole:23:in `<top (required)>'
```

```bash
$ ruby -v 
ruby 2.5.8p224 (2020-03-31 revision 67882) [x86_64-linux]
$ bundle exec ridgepole -v
ridgepole 0.8.12
$ psql -V
psql (PostgreSQL) 11.10 (Ubuntu 11.10-1.pgdg18.04+1)
```

I investigated it and notice:
 - The problem doesn't occur when I don't create non-primary key column as serial or bigserial.
 - The problem doesn't occur when create columns by `biging(or int4) GENERATED ALWAYS AS IDENTITY` even if non-primary key.

**Comment by altblanc** [comment]
typo

**Comment by winebarrel** [comment]
I have released v0.8.13 with the following fixes so please try it 🙏 
https://github.com/winebarrel/ridgepole/pull/321

**Comment by altblanc** [comment]
Thanks! I'll try it!

**Comment by winebarrel** [comment]
If you have any problems please re-open Issue 😃
