### ISSUE TITLE
Syntax errors with rails 5.0.0.beta3 and MySQL

### ISSUE THREAD

**Issue by makimoto** [winebarrel/ridgepole#78]
Hi,
I came across an exception when using ridgepole with rails (ActiveRecord) 5.0.0.beta3 and MySQL.

schema:
```sql
CREATE TABLE `foos` (
  `bar` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

`foos.schema` after `ridgepole --config config/database.yml --export --split --file Schemafile`:

```ruby
create_table "foos", id: false, force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8" do |t|
  t.datetime "bar", default: -> { "CURRENT_TIMESTAMP" }, null: false
end
```

and it causes syntax error in applying:

```
$ some_app b ridgepole --config config/database.yml --env test --apply --file Schemafile
Apply `Schemafile`
/Users/makimoto/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/ridgepole-325ceda2aeab/lib/ridgepole/delta.rb:106:in `instance_eval': <Schema>:1: syntax error, unexpected end-of-input (SyntaxError)
...e_app/foos.schema:2 (lambda)>})
...                               ^
	from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/ridgepole-325ceda2aeab/lib/ridgepole/delta.rb:106:in `block in eval_script'
	from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/ridgepole-325ceda2aeab/lib/ridgepole/delta.rb:167:in `with_pre_post_query'
	from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/ridgepole-325ceda2aeab/lib/ridgepole/delta.rb:104:in `eval_script'
	from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/ridgepole-325ceda2aeab/lib/ridgepole/delta.rb:94:in `migrate0'
	from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/ridgepole-325ceda2aeab/lib/ridgepole/delta.rb:19:in `migrate'
	from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/ridgepole-325ceda2aeab/bin/ridgepole:209:in `<top (required)>'
	from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bin/ridgepole:23:in `load'
	from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bin/ridgepole:23:in `<main>'
```

In my understanding, with rails 5.0.0.beta3, `DEFAULT CURRENT_TIMESTAMP` phrase is converted to a proc (`default: -> { "CURRENT_TIMESTAMP" }`) in the exporting phase and it is changed to inspected expression (like `#<Proc:xxx@42>`) in the applying phase.

Could you investigate on it? Thanks.

**Comment by winebarrel** [comment]
Fixed! 😄

**Comment by makimoto** [comment]
thank you!
